---
stages:
  - 'build-docker'
  - 'build-debs'
  - 'publish'

variables:
  DOCKER_IMAGE_TAG: $CI_REGISTRY_IMAGE:bookworm
  NUDGIS_BRANCH_PUBLISH: ng_unstable/bookworm

build_docker:
  image: registry.ubicast.net/docker/dind-compose
  stage: 'build-docker'
  # Docker images are built manually on demand
  when: manual
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE_TAG -f ci/debian/Dockerfile .
    - echo "Pushing $DOCKER_IMAGE_TAG"
    - docker push $DOCKER_IMAGE_TAG

build:
  image: $DOCKER_IMAGE_TAG
  stage: 'build-debs'
  before_script:
    - eval $(ssh-agent -s)
    - echo "$GST_CHANGE_DETECT_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - sed -i -Ee '$a\StrictHostKeyChecking accept-new' /etc/ssh/ssh_config
  script:
    - export GI_SCANNER_DISABLE_CACHE=1
    - mk-build-deps -irt 'apt-get --no-install-recommends -yV' debian/control > install-deps.log || (cat install-deps.log && exit 1)
    # We need https://github.com/mesonbuild/meson/pull/11337
    - pip install meson
    - debuild -e SSH_AUTH_SOCK -i -us -uc -b > debuild.log || (cat debuild.log && exit 1)
    - apt install -f $PWD/../*.deb -y > install.log || (cat install.log && exit 1)
    - mv $PWD/../*.deb .
    - gst-inspect-1.0

  artifacts:
    expire_in: 30 day
    when: always
    paths:
      - "*.log"
      - "*.deb"

publish:
  stage: 'publish'
  image: registry.ubicast.net/sys/debian-packaging-helper:bookworm
  when: manual
  script:
    - |
      VERSION=$(dpkg-parsechangelog | grep ^Version: | cut -d ' ' -f 2)
      DEBFILE=gstreamer-full1.0_${VERSION}_amd64.deb
      curl -X POST -H "api-key: ${SKYREACH_API_KEY}" -F "project=nudgis" -F "md5sum=$(md5sum ${DEBFILE} | awk '{print $1}')" -F "branch=${NUDGIS_BRANCH_PUBLISH}" -F "file=@${DEBFILE}" "https://skyreach.ubicast.net/api/v3/packaging/inbox/add/"

  dependencies:
    - build
