---
stages:
  - 'build-docker'
  - 'build-debs'


build_docker:
  image: registry.ubicast.net/docker/dind-compose
  stage: 'build-docker'
  # Docker images are built manually on demand
  when: manual
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG -f ci/debian/Dockerfile .
    - echo "Pushing $IMAGE_TAG"
    - docker push $IMAGE_TAG

build:
  image: registry.ubicast.net/public-projects/gstreamer1.0:1-19-3-ubicast
  stage: 'build-debs'
  before_script:
    - eval $(ssh-agent -s)
    - echo "$GST_CHANGE_DETECT_KEY" | tr -d '\r' | ssh-add - > /dev/null
  script:
    - export GI_SCANNER_DISABLE_CACHE=1
    - mk-build-deps -irt 'apt-get --no-install-recommends -yV' debian/control > install-deps.log || (cat install-deps.log && exit 1)
    - debuild -i -us -uc -b > debuild.log || (cat debuild.log && exit 1)
    - apt install -f $PWD/../*.deb -y > install.log || (cat install.log && exit 1)
    - mv $PWD/../*.deb .
    - gst-inspect-1.0
    - cp ../*.deb .

  artifacts:
    expire_in: 30 day
    when: always
    paths:
      - "*.log"
      - "*.deb"
