build:
  image: debian:buster
  script:
    - export GI_SCANNER_DISABLE_CACHE=1
    - rm -f ../*.deb
    - find /etc/apt/sources.list* -type f -exec sed -i 'p; s/^deb /deb-src /' '{}' +
    - apt update
    - apt-get install --no-install-recommends -yV build-essential devscripts equivs wget git
    - wget http://ftp.us.debian.org/debian/pool/main/m/meson/meson_0.60.2-1_all.deb
    - apt install -f $PWD/meson_*.deb -y && rm meson*.deb
    - mk-build-deps -irt 'apt-get --no-install-recommends -yV' debian/control > install-deps.log || (cat install-deps.log && exit 1)
    - debuild -i -us -uc -b > debuild.log || (cat debuild.log && exit 1)
    - apt install -f $PWD/../*.deb -y > install.log || (cat install.log && exit 1)
    - gst-inspect-1.0
    - cp ../*.deb .

  artifacts:
    expire_in: 30 day
    when: always
    paths:
      - "*.log"
      - "*.deb"
