# tools
usr/bin/*

# libgstreamer-full-1.0.so
usr/lib/*/libgstreamer-full-1.0.so

# helpers
usr/libexec/gstreamer-1.0

# python
usr/lib/python3/*

# Introspection
usr/lib/*/girepository-1.0

# Validate
usr/lib/*/gst-validate-launcher/*
usr/share/gstreamer-1.0/validate

# other resources
usr/share/gstreamer-1.0/encoding-profiles
usr/share/gstreamer-1.0/presets
usr/share/man
usr/share/gst-plugins-base/1.0/license-translations.dict
