debian/tmp/usr/lib/*/libgstreamer-full-1.0.so
debian/tmp/usr/lib/*/girepository-1.0/*
debian/tmp/usr/share/*/encoding-profiles/*/*
debian/tmp/usr/lib/python3/dist-packages/gi/*/*

debian/tmp/usr/bin/gst-inspect-1.0
debian/tmp/usr/bin/gst-launch-1.0
debian/tmp/usr/bin/ges-launch-1.0
debian/tmp/usr/bin/gst-typefind-1.0
debian/tmp/usr/bin/gst-validate-1.0
debian/tmp/usr/bin/gst-validate-media-check-1.0
debian/tmp/usr/bin/gst-validate-transcoding-1.0
debian/tmp/usr/bin/gst-validate-launcher

# Validate
debian/tmp/usr/lib/*/gst-validate-launcher/**
debian/tmp/usr/share/gstreamer-1.0/validate/**
