[built-in options]
# wrap_mode = 'default'
buildtype = 'debugoptimized'
default_library = 'static'
auto_features = 'disabled'
# prefer_static = true

[project options]
tools = 'enabled'
introspection = 'enabled'
gst-full = 'enabled'
package-name = 'GStreamer Ubicast build'
package-origin = 'https://git.ubicast.net/public-projects/gstreamer1.0'
# WARNING: see https://git.ubicast.net/gstreamer/gstreamer-scene-selector/-/issues/20
gpl = 'enabled'
libav = 'enabled'
ges = 'enabled'
devtools = 'enabled'
python = 'enabled'

[gstreamer:project options]
check = 'enabled'
glib_assert = 'true'
glib_checks = 'true'
extra-checks = 'enabled'

[gst-plugins-base:project options]
audioconvert = 'enabled'
audiomixer = 'enabled'
audiorate = 'enabled'
audioresample = 'enabled'
audiotestsrc = 'enabled'
compositor = 'enabled'
encoding = 'enabled'
gio = 'enabled'
ogg = 'enabled'
pbtypes = 'enabled'
playback = 'enabled'
typefind = 'enabled'
videoconvertscale = 'enabled'
videorate = 'enabled'
videotestsrc = 'enabled'
volume = 'enabled'
opus = 'enabled'
vorbis = 'enabled'

[gst-plugins-good:project options]
lame = 'enabled'
soup = 'enabled'
alpha = 'enabled'
audioparsers = 'enabled'
avi = 'enabled'
debugutils = 'enabled'
deinterlace = 'enabled'
flv = 'enabled'
id3demux = 'enabled'
imagefreeze = 'enabled'
interleave = 'enabled'
isomp4 = 'enabled'
level = 'enabled'
matroska = 'enabled'
multifile = 'enabled'
multipart = 'enabled'
smpte = 'enabled'
videobox = 'enabled'
videocrop = 'enabled'
videofilter = 'enabled'
wavparse = 'enabled'
oss = 'disabled'
oss4 = 'disabled'
vpx = 'enabled'
jpeg = 'enabled'

[gst-plugins-bad:project options]
audiofxbad = 'enabled'
autoconvert = 'enabled'
fdkaac = 'enabled'
id3tag = 'enabled'
interlace = 'enabled'
jpegformat = 'enabled'
mpegdemux = 'enabled'
mpegpsmux = 'enabled'
mpegtsdemux = 'enabled'
mpegtsmux = 'enabled'
mxf = 'enabled'
timecode = 'enabled'
transcode = 'enabled'
videofilters = 'enabled'
videoparsers = 'enabled'
openh264 = 'enabled'
hls = 'enabled'
opencv = 'enabled'
opus = 'enabled'
rtmp2 = 'enabled'
codectimestamper = 'enabled'

[gst-plugins-ugly:project options]
x264 = 'enabled'

[gst-editing-services:project options]
validate = 'enabled'
python = 'disabled'

[gst-devtools:project options]
validate = 'enabled'

[python:project options]

# [project:vpx options]
# vp8_decoder = 'enabled'
# vp9_decoder = 'enabled'

[json-glib:project options]
introspection = 'disabled'
tests = false

[FFmpeg:project options]
h264_decoder = 'enabled'
hevc_decoder = 'enabled'
wmv1_decoder = 'enabled'
wmv2_decoder = 'enabled'
vc1_decoder = 'enabled'
wmv3_decoder = 'enabled'
wmav1_decoder = 'enabled'
wmav2_decoder = 'enabled'
wmavoice_decoder = 'enabled'
h263_decoder = 'enabled'
h263_parser = 'enabled'
mpeg4_decoder = 'enabled'
mpeg4video_parser = 'enabled'
ac3_decoder = 'enabled'
ac3_parser = 'enabled'

# vi:set ft=meson:
